line-length = 120
target-version = "py312"
extend-exclude = [".venv"]

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
]

[per-file-target-version]
"**/*.py" = "py312"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true